spring:
  application:
    name: discover-service
server:
  port: 8761
eureka:
  instance:
    hostname: ${SERVER_HOSTNAME:localhost}
  client:
    fetch-registry: false
    register-with-eureka: false