server:
  port: 8081
jwt:
  secret: ENC(QE6dpps8uPs36LT/62AIOD4r2t1O/v4LsCLX5iiKXgzV10W9YzBUfvvKJAntH9cInm1hdS+Rqi5RBr4W/dQsxI/dItaWJJZNNlBL3S9rFhXEeP4PGtlwD7iiKZ9JOrVjDbkdg7ptZigWghUa23f74g==)
  lifetime: 86400000
spring:
  application:
    name: auth-service
jasypt:
  encryptor:
    password: spatifilum
logging:
  level:
    root: info
