version: '3.1'
services:
  discovery-service:
    build: discovery-service
    image: discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      SERVER_HOSTNAME: localhost

  api-gateway:
    build: api-gateway
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - record-service
      - order-service
      - user-service
      - storage-service

  record-service:
    build: record-service
    image: record-service
    container_name: record-service
    ports:
      - "8090:8090"
    depends_on:
      - discovery-service
      - records-db
      - storage-service
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://records-db:5432/records-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      REDIS_HOST: localhost
      REDIS_PORT: 6379

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  records-db:
    image: postgres:latest
    container_name: records-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: records-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  storage-service:
    build: storage-service
    image: storage-service
    container_name: storage-service
    ports:
      - "8084:8084"

  user-service:
    build: user-service
    image: user-service
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - users-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://users-db:5432/users-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVER: localhost:9092

  users-db:
    image: postgres:latest
    container_name: users-db
    ports:
      - "6551:5432"
    environment:
      POSTGRES_DB: records-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  mail-service:
    image: mail-service
    build: mail-service
    container_name: mail-service
    ports:
      - "8085:8085"
    environment:
      KAFKA_BOOTSTRAP_SERVER: localhost:9092

  order-service:
    build: order-service
    image: order-service
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - user-service
      - record-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://users-db:5432/users-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVER: localhost:9092