server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: country
          uri: lb://record-service
          predicates:
            - Path=/country/**
        - id: genre
          uri: lb://record-service
          predicates:
            - Path=/genre/**
        - id: performer
          uri: lb://record-service
          predicates:
            - Path=/performer/**
        - id: record
          uri: lb://record-service
          predicates:
            - Path=/record/**
        - id: unit
          uri: lb://record-service
          predicates:
            - Path=/unit/**
        - id: auth
          uri: lb://user-service
          predicates:
            - Path=/auth/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: storage
          uri: lb://s3storage-service
          predicates:
            - Path=/storage/**