jwt:
  secret: D3D4E47299E2B4E163FB62FC36DB5D75344DB95949574F0E64D9A404FF680BDA
server:
  port: 8080
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: country
          uri: lb://record-service
          predicates:
            - Path=/country/**
          filters:
            - AuthFilter

        - id: genre
          uri: lb://record-service
          predicates:
            - Path=/genre/**
          filters:
            - AuthFilter

        - id: performer
          uri: lb://record-service
          predicates:
            - Path=/performer/**
          filters:
            - AuthFilter

        - id: record
          uri: lb://record-service
          predicates:
            - Path=/record/**
          filters:
            - AuthFilter

        - id: unit
          uri: lb://record-service
          predicates:
            - Path=/unit/**
          filters:
            - AuthFilter

        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter

        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - AuthFilter

        - id: storage
          uri: lb://s3storage-service
          predicates:
            - Path=/storage/**
          filters:
            - AuthFilter
logging:
  level:
    root: info