server:
  port: 8085
spring:
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(rBSXTV7/U3M1ail5/zBd8vL0PbDrsUs7P+qlt+ezKjoS4/85DD1puuMGzQHqIy5RjrW+N+9KraJN336DBC31/w==)
    password: ENC(0xo1mjptY8ydzHJRYo2nOwa/8JxqKDCOFhRuBBocBFC3e0LCB49HYnqjqIOS0ESmmjJEHrhMRd0Lmma6fc0oAQ==)
    subject: Vinyl Store
    properties:
      mail.smtp:
          auth: true
          starttls.enable: true
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      properties:
        auto-offset-reset: earliest
        spring.json.trusted.packages: ru.xdpxrt.vinyl.dto.messageDTO
jasypt:
  encryptor:
    password: spatifilum