server:
  port: 8085
spring:
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: xdpxrt@gmail.com
    password: ipijeytdwphncqlt
    subject: Vinyl Store
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:true
  kafka:
    consumer:
      properties:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
        group-id: myGroup
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: ru.xdpxrt.vinyl.dto.messageDTO