server:
  port: 8085
spring:
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: xdpxrt@gmail.com
    password: rmmudrapytxgggzh
    subject: Vinyl Store
    properties:
      mail.smtp:
          auth: true
          starttls.enable: true
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      properties:
        auto-offset-reset: earliest
        spring.json.trusted.packages: ru.xdpxrt.vinyl.dto.messageDTO