server:
  port: 8090
jwt:
  secret: ENC(QE6dpps8uPs36LT/62AIOD4r2t1O/v4LsCLX5iiKXgzV10W9YzBUfvvKJAntH9cInm1hdS+Rqi5RBr4W/dQsxI/dItaWJJZNNlBL3S9rFhXEeP4PGtlwD7iiKZ9JOrVjDbkdg7ptZigWghUa23f74g==)
spring:
  application:
    name: record-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/records-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:iamgroot}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  sql:
    init:
      mode: always
  cache:
    type: redis
    redis:
      time-to-live: 60000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
jasypt:
  encryptor:
    password: spatifilum