server:
  port: 8084
spring:
  application:
    name: storage-service
aws:
  region: eu-north-1
  bucket: xdpxrt.vinyl.bucket
  credentials:
    access-key: AKIATCKARWLKMVK5RIOS
    secret_key: ENC(k6wbYtgFKM9+gJpTOM4IXgn0ZmCC6nkblSRrvJT830YWGILZiWAJOTdtRb9FoSyw/Xd3gpx5vMwHuXGgFNivoyd24bSZmug96Owfv1Ah5/Q=)
jasypt:
  encryptor:
    password: spatifilum
